title: The Life Sim Project
description: A project-based, life simulation personal financial management class!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  "Investopedia Stock Simulator 📈": 
    - https://www.investopedia.com/simulator/
aux_links_new_tab: true